version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Building the FastAPI backend application...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 290008131176.dkr.ecr.us-west-2.amazonaws.com/tracker_api

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Python FastAPI application...
      - docker build -t tracker_api .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker tag tracker_api:latest 290008131176.dkr.ecr.us-west-2.amazonaws.com/tracker_api
      - docker push 290008131176.dkr.ecr.us-west-2.amazonaws.com/tracker_api

artifacts:
  files:
    - "**/*"
  name: tracker_api-$(date +%Y-%m-%d)

cache:
  paths:
    - "/root/.cache/pip/**/*"
    - "/opt/venv/**/*"
