version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Building the FastAPI backend application...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 222907690579.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Python FastAPI application...
      - docker build -t trackerworkflow-api .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker tag trackerworkflow-api:latest 222907690579.dkr.ecr.us-west-2.amazonaws.com/trackerworkflow-api:latest
      - docker push 222907690579.dkr.ecr.us-west-2.amazonaws.com/trackerworkflow-api:latest

artifacts:
  files:
    - "**/*"
  name: trackerworkflow-api-$(date +%Y-%m-%d)

cache:
  paths:
    - "/root/.cache/pip/**/*"
    - "/opt/venv/**/*"
